pipeline:
  build:
    image: docker.io/alpine:3.14
    commands:
      - apk add cmark
      - ./build.sh
  deploy:
    image: docker.io/alpine:3.14
    commands:
      - apk add rsync openssh-client-default

      - eval $(ssh-agent -s)
      - echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - echo "[nulo.in]:420,[186.136.121.7]:420 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGPkgRVWYcVcgjI0xAjDgZQsYuXU9edcya8zna01ibyUMlfKHIMD9yOoq0R+fQPTCqwiol/2tKMPJ2hlKshc+H8=" > ~/.ssh/known_hosts

      - ./upload.sh
    when:
      branch: ANTIFASCISTA
      event: push
    secrets:
      - ssh_key
