pipeline:
  build-image:
    image: docker.io/woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      registry: https://gitea.nulo.in
      username: Nulo
      repo: gitea.nulo.in/nulo/sitio-build
      dockerfile: tooling/Containerfile
    when:
      path:
        include: ["tooling/*", ".woodpecker.yml"]

  build:
    image: gitea.nulo.in/nulo/sitio-build:latest
    pull: true
    commands:
      - pnpm install
      - ./tool refresh_feeds
      - ./tool check
      - ./tool build

      - |
        eval $(ssh-agent -s)
        echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        echo "[nulo.in]:420,[186.136.121.7]:420 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGPkgRVWYcVcgjI0xAjDgZQsYuXU9edcya8zna01ibyUMlfKHIMD9yOoq0R+fQPTCqwiol/2tKMPJ2hlKshc+H8=" > ~/.ssh/known_hosts

      - ./upload
    when:
      branch: ANTIFASCISTA
      event: push
    secrets:
      - ssh_key
