pipeline:
  build:
    image: docker.io/alpine:edge
    commands:
      - echo "172.17.0.1 alpine.proxy.coso" >> /etc/hosts
      - echo "http://alpine.proxy.coso/alpine/edge/main" > /etc/apk/repositories
      - echo "http://alpine.proxy.coso/alpine/edge/community" >> /etc/apk/repositories
      - echo "http://alpine.proxy.coso/alpine/edge/testing" >> /etc/apk/repositories
      - apk add musl-dev cmark-dev lua5.1 zig gcc

      - zig run compilar.zig -lc -lcmark
  deploy:
    image: docker.io/alpine:3.16
    commands:
      - echo "172.17.0.1 alpine.proxy.coso" >> /etc/hosts
      - echo "http://alpine.proxy.coso/alpine/v3.16/main" > /etc/apk/repositories
      - echo "http://alpine.proxy.coso/alpine/v3.16/community" >> /etc/apk/repositories
      - apk add rsync openssh-client-default

      - eval $(ssh-agent -s)
      - echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - echo "[nulo.in]:420,[186.136.121.7]:420 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGPkgRVWYcVcgjI0xAjDgZQsYuXU9edcya8zna01ibyUMlfKHIMD9yOoq0R+fQPTCqwiol/2tKMPJ2hlKshc+H8=" > ~/.ssh/known_hosts

      - ./upload.sh
    when:
      branch: ANTIFASCISTA
      event: push
    secrets:
      - ssh_key
