pipeline:
  setup:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - pnpm install
  check:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - ./tool check
    when:
      path:
        include: ["*.js", "*.ts", "package.json", "pnpm-lock.yaml", "tsconfig.json"]
  build:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - ./tool refresh_feeds
      - ./tool build
  upload:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - |
        eval $(ssh-agent -s)
        echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        echo "[dorsiblanco.nulo.in]:2223 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQEuHNIWQcS5La6lc2OvHQxZN6tRVtkts2wH1tfpola root@853c93d633a9" > ~/.ssh/known_hosts

      - rsync --rsh='ssh -p2223' --recursive --chmod=644 build/ root@dorsiblanco.nulo.in:/data/nulo_ar/
    secrets:
      - ssh_key
