pipeline:
  build:
    image: docker.io/alpine:3.17
    commands:
      - echo "172.17.0.1 npm.proxy.coso alpine.proxy.coso" >> /etc/hosts
      - echo "http://alpine.proxy.coso/alpine/v3.17/main" > /etc/apk/repositories
      - echo "http://alpine.proxy.coso/alpine/v3.17/community" >> /etc/apk/repositories
      - apk add curl nodejs npm lua5.1
      - curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm

      - pnpm set registry http://npm.proxy.coso
      - pnpm install
      - node compilar.js

      - apk add rsync openssh-client-default

      - eval $(ssh-agent -s)
      - echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - echo "[nulo.in]:420,[186.136.121.7]:420 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGPkgRVWYcVcgjI0xAjDgZQsYuXU9edcya8zna01ibyUMlfKHIMD9yOoq0R+fQPTCqwiol/2tKMPJ2hlKshc+H8=" > ~/.ssh/known_hosts

      - ./upload.sh
    when:
      branch: ANTIFASCISTA
      event: push
    secrets:
      - ssh_key
